version: '3.9'

services:
  api:
    build: .
    ports: 
      - 3000:3000
      - 9229:9229
    expose:
      - 3000
    environment:
      DATABASE_URL: postgres://postgres@postgres/api_dev
      NODE_ENV: development
    volumes:
      - ./bin:/app/bin
      - ./src:/app/src
      - /app/node_modules
    depends_on:
      - postgres
    command: npm run start:docker
  postgres:
    container_name: postgres
    image: postgres:14.3-alpine3.16
    restart: always
    environment:
      POSTGRES_DB: api_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes: 
      - pgdata4:/var/lib/postgresql/data
      - ./src/data-access/migrations:/docker-entrypoint-initdb.d
volumes:
  pgdata4: {}