name: Main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        # Docker Hub image
        image: postgres:14.3-alpine3.16
        # Provide the password for postgres
        env:
          POSTGRES_DB: api_dev
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.15.1"
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
        env:
          DATABASE_URL: postgres://postgres@postgres/api_dev
